// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ordering_packet.proto

#ifndef PROTOBUF_INCLUDED_ordering_5fpacket_2eproto
#define PROTOBUF_INCLUDED_ordering_5fpacket_2eproto

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3006001
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#define PROTOBUF_INTERNAL_EXPORT_protobuf_ordering_5fpacket_2eproto 

namespace protobuf_ordering_5fpacket_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
}  // namespace protobuf_ordering_5fpacket_2eproto
class Queuepacket;
class QueuepacketDefaultTypeInternal;
extern QueuepacketDefaultTypeInternal _Queuepacket_default_instance_;
namespace google {
namespace protobuf {
template<> ::Queuepacket* Arena::CreateMaybeMessage<::Queuepacket>(Arena*);
}  // namespace protobuf
}  // namespace google

// ===================================================================

class Queuepacket : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:Queuepacket) */ {
 public:
  Queuepacket();
  virtual ~Queuepacket();

  Queuepacket(const Queuepacket& from);

  inline Queuepacket& operator=(const Queuepacket& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  Queuepacket(Queuepacket&& from) noexcept
    : Queuepacket() {
    *this = ::std::move(from);
  }

  inline Queuepacket& operator=(Queuepacket&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Queuepacket& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Queuepacket* internal_default_instance() {
    return reinterpret_cast<const Queuepacket*>(
               &_Queuepacket_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  void Swap(Queuepacket* other);
  friend void swap(Queuepacket& a, Queuepacket& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline Queuepacket* New() const final {
    return CreateMaybeMessage<Queuepacket>(NULL);
  }

  Queuepacket* New(::google::protobuf::Arena* arena) const final {
    return CreateMaybeMessage<Queuepacket>(arena);
  }
  void CopyFrom(const ::google::protobuf::Message& from) final;
  void MergeFrom(const ::google::protobuf::Message& from) final;
  void CopyFrom(const Queuepacket& from);
  void MergeFrom(const Queuepacket& from);
  void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) final;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const final;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Queuepacket* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional string command = 1 [default = ""];
  bool has_command() const;
  void clear_command();
  static const int kCommandFieldNumber = 1;
  const ::std::string& command() const;
  void set_command(const ::std::string& value);
  #if LANG_CXX11
  void set_command(::std::string&& value);
  #endif
  void set_command(const char* value);
  void set_command(const char* value, size_t size);
  ::std::string* mutable_command();
  ::std::string* release_command();
  void set_allocated_command(::std::string* command);

  // optional string row = 2 [default = ""];
  bool has_row() const;
  void clear_row();
  static const int kRowFieldNumber = 2;
  const ::std::string& row() const;
  void set_row(const ::std::string& value);
  #if LANG_CXX11
  void set_row(::std::string&& value);
  #endif
  void set_row(const char* value);
  void set_row(const char* value, size_t size);
  ::std::string* mutable_row();
  ::std::string* release_row();
  void set_allocated_row(::std::string* row);

  // optional string column = 3 [default = ""];
  bool has_column() const;
  void clear_column();
  static const int kColumnFieldNumber = 3;
  const ::std::string& column() const;
  void set_column(const ::std::string& value);
  #if LANG_CXX11
  void set_column(::std::string&& value);
  #endif
  void set_column(const char* value);
  void set_column(const char* value, size_t size);
  ::std::string* mutable_column();
  ::std::string* release_column();
  void set_allocated_column(::std::string* column);

  // optional string data = 4 [default = ""];
  bool has_data() const;
  void clear_data();
  static const int kDataFieldNumber = 4;
  const ::std::string& data() const;
  void set_data(const ::std::string& value);
  #if LANG_CXX11
  void set_data(::std::string&& value);
  #endif
  void set_data(const char* value);
  void set_data(const char* value, size_t size);
  ::std::string* mutable_data();
  ::std::string* release_data();
  void set_allocated_data(::std::string* data);

  // optional string data_to_compare = 5 [default = ""];
  bool has_data_to_compare() const;
  void clear_data_to_compare();
  static const int kDataToCompareFieldNumber = 5;
  const ::std::string& data_to_compare() const;
  void set_data_to_compare(const ::std::string& value);
  #if LANG_CXX11
  void set_data_to_compare(::std::string&& value);
  #endif
  void set_data_to_compare(const char* value);
  void set_data_to_compare(const char* value, size_t size);
  ::std::string* mutable_data_to_compare();
  ::std::string* release_data_to_compare();
  void set_allocated_data_to_compare(::std::string* data_to_compare);

  // optional string msgid = 6 [default = ""];
  bool has_msgid() const;
  void clear_msgid();
  static const int kMsgidFieldNumber = 6;
  const ::std::string& msgid() const;
  void set_msgid(const ::std::string& value);
  #if LANG_CXX11
  void set_msgid(::std::string&& value);
  #endif
  void set_msgid(const char* value);
  void set_msgid(const char* value, size_t size);
  ::std::string* mutable_msgid();
  ::std::string* release_msgid();
  void set_allocated_msgid(::std::string* msgid);

  // optional int32 version_number = 7 [default = 0];
  bool has_version_number() const;
  void clear_version_number();
  static const int kVersionNumberFieldNumber = 7;
  ::google::protobuf::int32 version_number() const;
  void set_version_number(::google::protobuf::int32 value);

  // optional int32 sender_socket = 8 [default = 0];
  bool has_sender_socket() const;
  void clear_sender_socket();
  static const int kSenderSocketFieldNumber = 8;
  ::google::protobuf::int32 sender_socket() const;
  void set_sender_socket(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:Queuepacket)
 private:
  void set_has_command();
  void clear_has_command();
  void set_has_row();
  void clear_has_row();
  void set_has_column();
  void clear_has_column();
  void set_has_data();
  void clear_has_data();
  void set_has_data_to_compare();
  void clear_has_data_to_compare();
  void set_has_msgid();
  void clear_has_msgid();
  void set_has_version_number();
  void clear_has_version_number();
  void set_has_sender_socket();
  void clear_has_sender_socket();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable ::google::protobuf::internal::CachedSize _cached_size_;
  ::google::protobuf::internal::ArenaStringPtr command_;
  ::google::protobuf::internal::ArenaStringPtr row_;
  ::google::protobuf::internal::ArenaStringPtr column_;
  ::google::protobuf::internal::ArenaStringPtr data_;
  ::google::protobuf::internal::ArenaStringPtr data_to_compare_;
  ::google::protobuf::internal::ArenaStringPtr msgid_;
  ::google::protobuf::int32 version_number_;
  ::google::protobuf::int32 sender_socket_;
  friend struct ::protobuf_ordering_5fpacket_2eproto::TableStruct;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Queuepacket

// optional string command = 1 [default = ""];
inline bool Queuepacket::has_command() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void Queuepacket::set_has_command() {
  _has_bits_[0] |= 0x00000001u;
}
inline void Queuepacket::clear_has_command() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void Queuepacket::clear_command() {
  command_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_command();
}
inline const ::std::string& Queuepacket::command() const {
  // @@protoc_insertion_point(field_get:Queuepacket.command)
  return command_.GetNoArena();
}
inline void Queuepacket::set_command(const ::std::string& value) {
  set_has_command();
  command_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Queuepacket.command)
}
#if LANG_CXX11
inline void Queuepacket::set_command(::std::string&& value) {
  set_has_command();
  command_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Queuepacket.command)
}
#endif
inline void Queuepacket::set_command(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_command();
  command_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Queuepacket.command)
}
inline void Queuepacket::set_command(const char* value, size_t size) {
  set_has_command();
  command_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Queuepacket.command)
}
inline ::std::string* Queuepacket::mutable_command() {
  set_has_command();
  // @@protoc_insertion_point(field_mutable:Queuepacket.command)
  return command_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Queuepacket::release_command() {
  // @@protoc_insertion_point(field_release:Queuepacket.command)
  if (!has_command()) {
    return NULL;
  }
  clear_has_command();
  return command_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Queuepacket::set_allocated_command(::std::string* command) {
  if (command != NULL) {
    set_has_command();
  } else {
    clear_has_command();
  }
  command_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), command);
  // @@protoc_insertion_point(field_set_allocated:Queuepacket.command)
}

// optional string row = 2 [default = ""];
inline bool Queuepacket::has_row() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void Queuepacket::set_has_row() {
  _has_bits_[0] |= 0x00000002u;
}
inline void Queuepacket::clear_has_row() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void Queuepacket::clear_row() {
  row_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_row();
}
inline const ::std::string& Queuepacket::row() const {
  // @@protoc_insertion_point(field_get:Queuepacket.row)
  return row_.GetNoArena();
}
inline void Queuepacket::set_row(const ::std::string& value) {
  set_has_row();
  row_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Queuepacket.row)
}
#if LANG_CXX11
inline void Queuepacket::set_row(::std::string&& value) {
  set_has_row();
  row_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Queuepacket.row)
}
#endif
inline void Queuepacket::set_row(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_row();
  row_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Queuepacket.row)
}
inline void Queuepacket::set_row(const char* value, size_t size) {
  set_has_row();
  row_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Queuepacket.row)
}
inline ::std::string* Queuepacket::mutable_row() {
  set_has_row();
  // @@protoc_insertion_point(field_mutable:Queuepacket.row)
  return row_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Queuepacket::release_row() {
  // @@protoc_insertion_point(field_release:Queuepacket.row)
  if (!has_row()) {
    return NULL;
  }
  clear_has_row();
  return row_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Queuepacket::set_allocated_row(::std::string* row) {
  if (row != NULL) {
    set_has_row();
  } else {
    clear_has_row();
  }
  row_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), row);
  // @@protoc_insertion_point(field_set_allocated:Queuepacket.row)
}

// optional string column = 3 [default = ""];
inline bool Queuepacket::has_column() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void Queuepacket::set_has_column() {
  _has_bits_[0] |= 0x00000004u;
}
inline void Queuepacket::clear_has_column() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void Queuepacket::clear_column() {
  column_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_column();
}
inline const ::std::string& Queuepacket::column() const {
  // @@protoc_insertion_point(field_get:Queuepacket.column)
  return column_.GetNoArena();
}
inline void Queuepacket::set_column(const ::std::string& value) {
  set_has_column();
  column_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Queuepacket.column)
}
#if LANG_CXX11
inline void Queuepacket::set_column(::std::string&& value) {
  set_has_column();
  column_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Queuepacket.column)
}
#endif
inline void Queuepacket::set_column(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_column();
  column_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Queuepacket.column)
}
inline void Queuepacket::set_column(const char* value, size_t size) {
  set_has_column();
  column_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Queuepacket.column)
}
inline ::std::string* Queuepacket::mutable_column() {
  set_has_column();
  // @@protoc_insertion_point(field_mutable:Queuepacket.column)
  return column_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Queuepacket::release_column() {
  // @@protoc_insertion_point(field_release:Queuepacket.column)
  if (!has_column()) {
    return NULL;
  }
  clear_has_column();
  return column_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Queuepacket::set_allocated_column(::std::string* column) {
  if (column != NULL) {
    set_has_column();
  } else {
    clear_has_column();
  }
  column_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), column);
  // @@protoc_insertion_point(field_set_allocated:Queuepacket.column)
}

// optional string data = 4 [default = ""];
inline bool Queuepacket::has_data() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void Queuepacket::set_has_data() {
  _has_bits_[0] |= 0x00000008u;
}
inline void Queuepacket::clear_has_data() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void Queuepacket::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_data();
}
inline const ::std::string& Queuepacket::data() const {
  // @@protoc_insertion_point(field_get:Queuepacket.data)
  return data_.GetNoArena();
}
inline void Queuepacket::set_data(const ::std::string& value) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Queuepacket.data)
}
#if LANG_CXX11
inline void Queuepacket::set_data(::std::string&& value) {
  set_has_data();
  data_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Queuepacket.data)
}
#endif
inline void Queuepacket::set_data(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Queuepacket.data)
}
inline void Queuepacket::set_data(const char* value, size_t size) {
  set_has_data();
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Queuepacket.data)
}
inline ::std::string* Queuepacket::mutable_data() {
  set_has_data();
  // @@protoc_insertion_point(field_mutable:Queuepacket.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Queuepacket::release_data() {
  // @@protoc_insertion_point(field_release:Queuepacket.data)
  if (!has_data()) {
    return NULL;
  }
  clear_has_data();
  return data_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Queuepacket::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    set_has_data();
  } else {
    clear_has_data();
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:Queuepacket.data)
}

// optional string data_to_compare = 5 [default = ""];
inline bool Queuepacket::has_data_to_compare() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void Queuepacket::set_has_data_to_compare() {
  _has_bits_[0] |= 0x00000010u;
}
inline void Queuepacket::clear_has_data_to_compare() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void Queuepacket::clear_data_to_compare() {
  data_to_compare_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_data_to_compare();
}
inline const ::std::string& Queuepacket::data_to_compare() const {
  // @@protoc_insertion_point(field_get:Queuepacket.data_to_compare)
  return data_to_compare_.GetNoArena();
}
inline void Queuepacket::set_data_to_compare(const ::std::string& value) {
  set_has_data_to_compare();
  data_to_compare_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Queuepacket.data_to_compare)
}
#if LANG_CXX11
inline void Queuepacket::set_data_to_compare(::std::string&& value) {
  set_has_data_to_compare();
  data_to_compare_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Queuepacket.data_to_compare)
}
#endif
inline void Queuepacket::set_data_to_compare(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_data_to_compare();
  data_to_compare_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Queuepacket.data_to_compare)
}
inline void Queuepacket::set_data_to_compare(const char* value, size_t size) {
  set_has_data_to_compare();
  data_to_compare_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Queuepacket.data_to_compare)
}
inline ::std::string* Queuepacket::mutable_data_to_compare() {
  set_has_data_to_compare();
  // @@protoc_insertion_point(field_mutable:Queuepacket.data_to_compare)
  return data_to_compare_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Queuepacket::release_data_to_compare() {
  // @@protoc_insertion_point(field_release:Queuepacket.data_to_compare)
  if (!has_data_to_compare()) {
    return NULL;
  }
  clear_has_data_to_compare();
  return data_to_compare_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Queuepacket::set_allocated_data_to_compare(::std::string* data_to_compare) {
  if (data_to_compare != NULL) {
    set_has_data_to_compare();
  } else {
    clear_has_data_to_compare();
  }
  data_to_compare_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data_to_compare);
  // @@protoc_insertion_point(field_set_allocated:Queuepacket.data_to_compare)
}

// optional string msgid = 6 [default = ""];
inline bool Queuepacket::has_msgid() const {
  return (_has_bits_[0] & 0x00000020u) != 0;
}
inline void Queuepacket::set_has_msgid() {
  _has_bits_[0] |= 0x00000020u;
}
inline void Queuepacket::clear_has_msgid() {
  _has_bits_[0] &= ~0x00000020u;
}
inline void Queuepacket::clear_msgid() {
  msgid_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  clear_has_msgid();
}
inline const ::std::string& Queuepacket::msgid() const {
  // @@protoc_insertion_point(field_get:Queuepacket.msgid)
  return msgid_.GetNoArena();
}
inline void Queuepacket::set_msgid(const ::std::string& value) {
  set_has_msgid();
  msgid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Queuepacket.msgid)
}
#if LANG_CXX11
inline void Queuepacket::set_msgid(::std::string&& value) {
  set_has_msgid();
  msgid_.SetNoArena(
    &::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::move(value));
  // @@protoc_insertion_point(field_set_rvalue:Queuepacket.msgid)
}
#endif
inline void Queuepacket::set_msgid(const char* value) {
  GOOGLE_DCHECK(value != NULL);
  set_has_msgid();
  msgid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Queuepacket.msgid)
}
inline void Queuepacket::set_msgid(const char* value, size_t size) {
  set_has_msgid();
  msgid_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Queuepacket.msgid)
}
inline ::std::string* Queuepacket::mutable_msgid() {
  set_has_msgid();
  // @@protoc_insertion_point(field_mutable:Queuepacket.msgid)
  return msgid_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline ::std::string* Queuepacket::release_msgid() {
  // @@protoc_insertion_point(field_release:Queuepacket.msgid)
  if (!has_msgid()) {
    return NULL;
  }
  clear_has_msgid();
  return msgid_.ReleaseNonDefaultNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
inline void Queuepacket::set_allocated_msgid(::std::string* msgid) {
  if (msgid != NULL) {
    set_has_msgid();
  } else {
    clear_has_msgid();
  }
  msgid_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), msgid);
  // @@protoc_insertion_point(field_set_allocated:Queuepacket.msgid)
}

// optional int32 version_number = 7 [default = 0];
inline bool Queuepacket::has_version_number() const {
  return (_has_bits_[0] & 0x00000040u) != 0;
}
inline void Queuepacket::set_has_version_number() {
  _has_bits_[0] |= 0x00000040u;
}
inline void Queuepacket::clear_has_version_number() {
  _has_bits_[0] &= ~0x00000040u;
}
inline void Queuepacket::clear_version_number() {
  version_number_ = 0;
  clear_has_version_number();
}
inline ::google::protobuf::int32 Queuepacket::version_number() const {
  // @@protoc_insertion_point(field_get:Queuepacket.version_number)
  return version_number_;
}
inline void Queuepacket::set_version_number(::google::protobuf::int32 value) {
  set_has_version_number();
  version_number_ = value;
  // @@protoc_insertion_point(field_set:Queuepacket.version_number)
}

// optional int32 sender_socket = 8 [default = 0];
inline bool Queuepacket::has_sender_socket() const {
  return (_has_bits_[0] & 0x00000080u) != 0;
}
inline void Queuepacket::set_has_sender_socket() {
  _has_bits_[0] |= 0x00000080u;
}
inline void Queuepacket::clear_has_sender_socket() {
  _has_bits_[0] &= ~0x00000080u;
}
inline void Queuepacket::clear_sender_socket() {
  sender_socket_ = 0;
  clear_has_sender_socket();
}
inline ::google::protobuf::int32 Queuepacket::sender_socket() const {
  // @@protoc_insertion_point(field_get:Queuepacket.sender_socket)
  return sender_socket_;
}
inline void Queuepacket::set_sender_socket(::google::protobuf::int32 value) {
  set_has_sender_socket();
  sender_socket_ = value;
  // @@protoc_insertion_point(field_set:Queuepacket.sender_socket)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_INCLUDED_ordering_5fpacket_2eproto
