// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: replication_packet.proto

#include "replication_packet.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

class RepPacketDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<RepPacket>
      _instance;
} _RepPacket_default_instance_;
namespace protobuf_replication_5fpacket_2eproto {
static void InitDefaultsRepPacket() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::_RepPacket_default_instance_;
    new (ptr) ::RepPacket();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::RepPacket::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_RepPacket =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsRepPacket}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_RepPacket.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::RepPacket, _has_bits_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::RepPacket, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::RepPacket, command_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::RepPacket, request_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::RepPacket, row_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::RepPacket, column_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::RepPacket, data_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::RepPacket, data_to_compare_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::RepPacket, msgid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::RepPacket, proposed_number_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::RepPacket, version_number_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::RepPacket, deliverable_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::RepPacket, senderid_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::RepPacket, sender_),
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  8,
  9,
  10,
  11,
  7,
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, 17, sizeof(::RepPacket)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::_RepPacket_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "replication_packet.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\030replication_packet.proto\"\204\002\n\tRepPacket"
      "\022\021\n\007command\030\001 \001(\t:\000\022\021\n\007request\030\002 \001(\t:\000\022\r"
      "\n\003row\030\003 \001(\t:\000\022\020\n\006column\030\004 \001(\t:\000\022\016\n\004data\030"
      "\005 \001(\t:\000\022\031\n\017data_to_compare\030\006 \001(\t:\000\022\017\n\005ms"
      "gid\030\007 \001(\t:\000\022\032\n\017proposed_number\030\010 \001(\005:\0010\022"
      "\031\n\016version_number\030\t \001(\005:\0010\022\026\n\013deliverabl"
      "e\030\n \001(\005:\0010\022\023\n\010senderid\030\013 \001(\005:\0010\022\020\n\006sende"
      "r\030\014 \001(\t:\000"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 289);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "replication_packet.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_replication_5fpacket_2eproto

// ===================================================================

void RepPacket::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int RepPacket::kCommandFieldNumber;
const int RepPacket::kRequestFieldNumber;
const int RepPacket::kRowFieldNumber;
const int RepPacket::kColumnFieldNumber;
const int RepPacket::kDataFieldNumber;
const int RepPacket::kDataToCompareFieldNumber;
const int RepPacket::kMsgidFieldNumber;
const int RepPacket::kProposedNumberFieldNumber;
const int RepPacket::kVersionNumberFieldNumber;
const int RepPacket::kDeliverableFieldNumber;
const int RepPacket::kSenderidFieldNumber;
const int RepPacket::kSenderFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

RepPacket::RepPacket()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_replication_5fpacket_2eproto::scc_info_RepPacket.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:RepPacket)
}
RepPacket::RepPacket(const RepPacket& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      _has_bits_(from._has_bits_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  command_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_command()) {
    command_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.command_);
  }
  request_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_request()) {
    request_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.request_);
  }
  row_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_row()) {
    row_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.row_);
  }
  column_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_column()) {
    column_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.column_);
  }
  data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_data()) {
    data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.data_);
  }
  data_to_compare_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_data_to_compare()) {
    data_to_compare_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.data_to_compare_);
  }
  msgid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_msgid()) {
    msgid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.msgid_);
  }
  sender_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.has_sender()) {
    sender_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sender_);
  }
  ::memcpy(&proposed_number_, &from.proposed_number_,
    static_cast<size_t>(reinterpret_cast<char*>(&senderid_) -
    reinterpret_cast<char*>(&proposed_number_)) + sizeof(senderid_));
  // @@protoc_insertion_point(copy_constructor:RepPacket)
}

void RepPacket::SharedCtor() {
  command_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  request_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  row_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  column_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  data_to_compare_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  msgid_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sender_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  ::memset(&proposed_number_, 0, static_cast<size_t>(
      reinterpret_cast<char*>(&senderid_) -
      reinterpret_cast<char*>(&proposed_number_)) + sizeof(senderid_));
}

RepPacket::~RepPacket() {
  // @@protoc_insertion_point(destructor:RepPacket)
  SharedDtor();
}

void RepPacket::SharedDtor() {
  command_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  request_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  row_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  column_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  data_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  data_to_compare_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  msgid_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  sender_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void RepPacket::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* RepPacket::descriptor() {
  ::protobuf_replication_5fpacket_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_replication_5fpacket_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const RepPacket& RepPacket::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_replication_5fpacket_2eproto::scc_info_RepPacket.base);
  return *internal_default_instance();
}


void RepPacket::Clear() {
// @@protoc_insertion_point(message_clear_start:RepPacket)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  if (cached_has_bits & 255u) {
    if (cached_has_bits & 0x00000001u) {
      command_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000002u) {
      request_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000004u) {
      row_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000008u) {
      column_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000010u) {
      data_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000020u) {
      data_to_compare_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000040u) {
      msgid_.ClearNonDefaultToEmptyNoArena();
    }
    if (cached_has_bits & 0x00000080u) {
      sender_.ClearNonDefaultToEmptyNoArena();
    }
  }
  if (cached_has_bits & 3840u) {
    ::memset(&proposed_number_, 0, static_cast<size_t>(
        reinterpret_cast<char*>(&senderid_) -
        reinterpret_cast<char*>(&proposed_number_)) + sizeof(senderid_));
  }
  _has_bits_.Clear();
  _internal_metadata_.Clear();
}

bool RepPacket::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:RepPacket)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string command = 1 [default = ""];
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_command()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->command().data(), static_cast<int>(this->command().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "RepPacket.command");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string request = 2 [default = ""];
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_request()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->request().data(), static_cast<int>(this->request().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "RepPacket.request");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string row = 3 [default = ""];
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(26u /* 26 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_row()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->row().data(), static_cast<int>(this->row().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "RepPacket.row");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string column = 4 [default = ""];
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(34u /* 34 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_column()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->column().data(), static_cast<int>(this->column().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "RepPacket.column");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string data = 5 [default = ""];
      case 5: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(42u /* 42 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_data()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->data().data(), static_cast<int>(this->data().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "RepPacket.data");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string data_to_compare = 6 [default = ""];
      case 6: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(50u /* 50 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_data_to_compare()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->data_to_compare().data(), static_cast<int>(this->data_to_compare().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "RepPacket.data_to_compare");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string msgid = 7 [default = ""];
      case 7: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(58u /* 58 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_msgid()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->msgid().data(), static_cast<int>(this->msgid().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "RepPacket.msgid");
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 proposed_number = 8 [default = 0];
      case 8: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(64u /* 64 & 0xFF */)) {
          set_has_proposed_number();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &proposed_number_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 version_number = 9 [default = 0];
      case 9: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(72u /* 72 & 0xFF */)) {
          set_has_version_number();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &version_number_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 deliverable = 10 [default = 0];
      case 10: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(80u /* 80 & 0xFF */)) {
          set_has_deliverable();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &deliverable_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional int32 senderid = 11 [default = 0];
      case 11: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(88u /* 88 & 0xFF */)) {
          set_has_senderid();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   ::google::protobuf::int32, ::google::protobuf::internal::WireFormatLite::TYPE_INT32>(
                 input, &senderid_)));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // optional string sender = 12 [default = ""];
      case 12: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(98u /* 98 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_sender()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->sender().data(), static_cast<int>(this->sender().length()),
            ::google::protobuf::internal::WireFormat::PARSE,
            "RepPacket.sender");
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:RepPacket)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:RepPacket)
  return false;
#undef DO_
}

void RepPacket::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:RepPacket)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string command = 1 [default = ""];
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->command().data(), static_cast<int>(this->command().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "RepPacket.command");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->command(), output);
  }

  // optional string request = 2 [default = ""];
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->request().data(), static_cast<int>(this->request().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "RepPacket.request");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->request(), output);
  }

  // optional string row = 3 [default = ""];
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->row().data(), static_cast<int>(this->row().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "RepPacket.row");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      3, this->row(), output);
  }

  // optional string column = 4 [default = ""];
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->column().data(), static_cast<int>(this->column().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "RepPacket.column");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->column(), output);
  }

  // optional string data = 5 [default = ""];
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->data().data(), static_cast<int>(this->data().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "RepPacket.data");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      5, this->data(), output);
  }

  // optional string data_to_compare = 6 [default = ""];
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->data_to_compare().data(), static_cast<int>(this->data_to_compare().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "RepPacket.data_to_compare");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      6, this->data_to_compare(), output);
  }

  // optional string msgid = 7 [default = ""];
  if (cached_has_bits & 0x00000040u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->msgid().data(), static_cast<int>(this->msgid().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "RepPacket.msgid");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      7, this->msgid(), output);
  }

  // optional int32 proposed_number = 8 [default = 0];
  if (cached_has_bits & 0x00000100u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(8, this->proposed_number(), output);
  }

  // optional int32 version_number = 9 [default = 0];
  if (cached_has_bits & 0x00000200u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(9, this->version_number(), output);
  }

  // optional int32 deliverable = 10 [default = 0];
  if (cached_has_bits & 0x00000400u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(10, this->deliverable(), output);
  }

  // optional int32 senderid = 11 [default = 0];
  if (cached_has_bits & 0x00000800u) {
    ::google::protobuf::internal::WireFormatLite::WriteInt32(11, this->senderid(), output);
  }

  // optional string sender = 12 [default = ""];
  if (cached_has_bits & 0x00000080u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->sender().data(), static_cast<int>(this->sender().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "RepPacket.sender");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      12, this->sender(), output);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        _internal_metadata_.unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:RepPacket)
}

::google::protobuf::uint8* RepPacket::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:RepPacket)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = _has_bits_[0];
  // optional string command = 1 [default = ""];
  if (cached_has_bits & 0x00000001u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->command().data(), static_cast<int>(this->command().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "RepPacket.command");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->command(), target);
  }

  // optional string request = 2 [default = ""];
  if (cached_has_bits & 0x00000002u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->request().data(), static_cast<int>(this->request().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "RepPacket.request");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->request(), target);
  }

  // optional string row = 3 [default = ""];
  if (cached_has_bits & 0x00000004u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->row().data(), static_cast<int>(this->row().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "RepPacket.row");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        3, this->row(), target);
  }

  // optional string column = 4 [default = ""];
  if (cached_has_bits & 0x00000008u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->column().data(), static_cast<int>(this->column().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "RepPacket.column");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->column(), target);
  }

  // optional string data = 5 [default = ""];
  if (cached_has_bits & 0x00000010u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->data().data(), static_cast<int>(this->data().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "RepPacket.data");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        5, this->data(), target);
  }

  // optional string data_to_compare = 6 [default = ""];
  if (cached_has_bits & 0x00000020u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->data_to_compare().data(), static_cast<int>(this->data_to_compare().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "RepPacket.data_to_compare");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        6, this->data_to_compare(), target);
  }

  // optional string msgid = 7 [default = ""];
  if (cached_has_bits & 0x00000040u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->msgid().data(), static_cast<int>(this->msgid().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "RepPacket.msgid");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        7, this->msgid(), target);
  }

  // optional int32 proposed_number = 8 [default = 0];
  if (cached_has_bits & 0x00000100u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(8, this->proposed_number(), target);
  }

  // optional int32 version_number = 9 [default = 0];
  if (cached_has_bits & 0x00000200u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(9, this->version_number(), target);
  }

  // optional int32 deliverable = 10 [default = 0];
  if (cached_has_bits & 0x00000400u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(10, this->deliverable(), target);
  }

  // optional int32 senderid = 11 [default = 0];
  if (cached_has_bits & 0x00000800u) {
    target = ::google::protobuf::internal::WireFormatLite::WriteInt32ToArray(11, this->senderid(), target);
  }

  // optional string sender = 12 [default = ""];
  if (cached_has_bits & 0x00000080u) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->sender().data(), static_cast<int>(this->sender().length()),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "RepPacket.sender");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        12, this->sender(), target);
  }

  if (_internal_metadata_.have_unknown_fields()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        _internal_metadata_.unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:RepPacket)
  return target;
}

size_t RepPacket::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:RepPacket)
  size_t total_size = 0;

  if (_internal_metadata_.have_unknown_fields()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        _internal_metadata_.unknown_fields());
  }
  if (_has_bits_[0 / 32] & 255u) {
    // optional string command = 1 [default = ""];
    if (has_command()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->command());
    }

    // optional string request = 2 [default = ""];
    if (has_request()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->request());
    }

    // optional string row = 3 [default = ""];
    if (has_row()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->row());
    }

    // optional string column = 4 [default = ""];
    if (has_column()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->column());
    }

    // optional string data = 5 [default = ""];
    if (has_data()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->data());
    }

    // optional string data_to_compare = 6 [default = ""];
    if (has_data_to_compare()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->data_to_compare());
    }

    // optional string msgid = 7 [default = ""];
    if (has_msgid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->msgid());
    }

    // optional string sender = 12 [default = ""];
    if (has_sender()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::StringSize(
          this->sender());
    }

  }
  if (_has_bits_[8 / 32] & 3840u) {
    // optional int32 proposed_number = 8 [default = 0];
    if (has_proposed_number()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->proposed_number());
    }

    // optional int32 version_number = 9 [default = 0];
    if (has_version_number()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->version_number());
    }

    // optional int32 deliverable = 10 [default = 0];
    if (has_deliverable()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->deliverable());
    }

    // optional int32 senderid = 11 [default = 0];
    if (has_senderid()) {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::Int32Size(
          this->senderid());
    }

  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void RepPacket::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:RepPacket)
  GOOGLE_DCHECK_NE(&from, this);
  const RepPacket* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const RepPacket>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:RepPacket)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:RepPacket)
    MergeFrom(*source);
  }
}

void RepPacket::MergeFrom(const RepPacket& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:RepPacket)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  cached_has_bits = from._has_bits_[0];
  if (cached_has_bits & 255u) {
    if (cached_has_bits & 0x00000001u) {
      set_has_command();
      command_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.command_);
    }
    if (cached_has_bits & 0x00000002u) {
      set_has_request();
      request_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.request_);
    }
    if (cached_has_bits & 0x00000004u) {
      set_has_row();
      row_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.row_);
    }
    if (cached_has_bits & 0x00000008u) {
      set_has_column();
      column_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.column_);
    }
    if (cached_has_bits & 0x00000010u) {
      set_has_data();
      data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.data_);
    }
    if (cached_has_bits & 0x00000020u) {
      set_has_data_to_compare();
      data_to_compare_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.data_to_compare_);
    }
    if (cached_has_bits & 0x00000040u) {
      set_has_msgid();
      msgid_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.msgid_);
    }
    if (cached_has_bits & 0x00000080u) {
      set_has_sender();
      sender_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.sender_);
    }
  }
  if (cached_has_bits & 3840u) {
    if (cached_has_bits & 0x00000100u) {
      proposed_number_ = from.proposed_number_;
    }
    if (cached_has_bits & 0x00000200u) {
      version_number_ = from.version_number_;
    }
    if (cached_has_bits & 0x00000400u) {
      deliverable_ = from.deliverable_;
    }
    if (cached_has_bits & 0x00000800u) {
      senderid_ = from.senderid_;
    }
    _has_bits_[0] |= cached_has_bits;
  }
}

void RepPacket::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:RepPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void RepPacket::CopyFrom(const RepPacket& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:RepPacket)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool RepPacket::IsInitialized() const {
  return true;
}

void RepPacket::Swap(RepPacket* other) {
  if (other == this) return;
  InternalSwap(other);
}
void RepPacket::InternalSwap(RepPacket* other) {
  using std::swap;
  command_.Swap(&other->command_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  request_.Swap(&other->request_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  row_.Swap(&other->row_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  column_.Swap(&other->column_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  data_.Swap(&other->data_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  data_to_compare_.Swap(&other->data_to_compare_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  msgid_.Swap(&other->msgid_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  sender_.Swap(&other->sender_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  swap(proposed_number_, other->proposed_number_);
  swap(version_number_, other->version_number_);
  swap(deliverable_, other->deliverable_);
  swap(senderid_, other->senderid_);
  swap(_has_bits_[0], other->_has_bits_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata RepPacket::GetMetadata() const {
  protobuf_replication_5fpacket_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_replication_5fpacket_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::RepPacket* Arena::CreateMaybeMessage< ::RepPacket >(Arena* arena) {
  return Arena::CreateInternal< ::RepPacket >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
